 # installed by `gem jekyll`
gem "webrick"        # required when using Ruby >= 3 and Jekyll <= 4.2.2


source 'https://rubygems.org'
gem 'jekyll', '~> 4.2.0'

# Add this line to your Gemfile
gem 'wdm', '>= 0.1.0' if Gem.win_platform?



gem "just-the-docs", "0.5.3" # pinned to the current release
# gem "just-the-docs"        # always download the latest release

# If you have any plugins, put them here!
group :jekyll_plugins do
    gem "kramdown"
    gem "kramdown-parser-gfm"
    gem "jekyll-remote-theme"
end