# This is a basic workflow to help you get started with Actions
name: Copy Files to /docs

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Copy files excluding /docs to /docs
      run: |
        mkdir -p docs
        rsync -av --exclude='docs/' --exclude='.github/' ./ docs/

    - name: Commit and Push Changes
      run: |
        git config --global user.name 'Samuel Van Ackere'
        git config --global user.email 'samuel.vanackere@vlaanderen.be'
        git add docs/
        git commit -m "Update documents in /docs" || echo "No changes to commit"
        git push
